# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reviewbot.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0freviewbot.proto\"B\n\x0fMessageTemplate\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x10\n\x08triggers\x18\x03 \x03(\t\"%\n\x15\x44\x65leteTemplateRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x16\n\x14ListTemplatesRequest\"7\n\x10TemplateResponse\x12#\n\ttemplates\x18\x01 \x03(\x0b\x32\x10.MessageTemplate\"R\n\x12SendMessageRequest\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t\x12\x15\n\rtemplate_name\x18\x03 \x01(\t\"&\n\x13SendMessageResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xd8\x01\n\tTemplates\x12/\n\x06\x43reate\x12\x10.MessageTemplate\x1a\x11.TemplateResponse\"\x00\x12/\n\x06Update\x12\x10.MessageTemplate\x1a\x11.TemplateResponse\"\x00\x12\x35\n\x06\x44\x65lete\x12\x16.DeleteTemplateRequest\x1a\x11.TemplateResponse\"\x00\x12\x32\n\x04List\x12\x15.ListTemplatesRequest\x1a\x11.TemplateResponse\"\x00\x32>\n\x07Message\x12\x33\n\x04Send\x12\x13.SendMessageRequest\x1a\x14.SendMessageResponse\"\x00\x42%Z#reviewbot/internal/app/reviewbot/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'reviewbot_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z#reviewbot/internal/app/reviewbot/pb'
  _globals['_MESSAGETEMPLATE']._serialized_start=19
  _globals['_MESSAGETEMPLATE']._serialized_end=85
  _globals['_DELETETEMPLATEREQUEST']._serialized_start=87
  _globals['_DELETETEMPLATEREQUEST']._serialized_end=124
  _globals['_LISTTEMPLATESREQUEST']._serialized_start=126
  _globals['_LISTTEMPLATESREQUEST']._serialized_end=148
  _globals['_TEMPLATERESPONSE']._serialized_start=150
  _globals['_TEMPLATERESPONSE']._serialized_end=205
  _globals['_SENDMESSAGEREQUEST']._serialized_start=207
  _globals['_SENDMESSAGEREQUEST']._serialized_end=289
  _globals['_SENDMESSAGERESPONSE']._serialized_start=291
  _globals['_SENDMESSAGERESPONSE']._serialized_end=329
  _globals['_TEMPLATES']._serialized_start=332
  _globals['_TEMPLATES']._serialized_end=548
  _globals['_MESSAGE']._serialized_start=550
  _globals['_MESSAGE']._serialized_end=612
# @@protoc_insertion_point(module_scope)
